Add a parameter for the number of max connections per file
EGA-archive/ega-fuse pull request #9
Opened 2020-07-24 13:11 UTC by anandmohan777

2020-07-28 07:55 UTC, afoix approved these changes
LGTM!

2020-07-30 15:35 UTC, jorizci requested changes

2020-07-30 15:35 UTC, jorizci commented on src/main/java/uk/ac/ebi/ega/egafuse/config/EgaFuseApplicationConfig.java
> +                        .executor(Executors.newFixedThreadPool(cachePrefetch))
Technically the size of the executor should be max connections. Remember that we can prefetch N chunks but the user can still try to access more files.

2020-07-30 15:41 UTC, malloryfreeberg commented on README.md
> +* c : total max connections, total number of API connections used by the application, default value: 4
I suggest:
`c : maximum number of API connections used by the application, default value: 4`

2020-07-30 15:42 UTC, malloryfreeberg commented on README.md
> +* cpf : connections per file, download a file using only specified number of connections, default value: 2, `preferably, c (total max connections)  >= cpf (connections per file)`
I suggest:
`cpf : connections per file, download a file using the specified number of connections, default value: 2`

2020-08-03 08:29 UTC, jorizci approved these changes

2020-08-03 08:31 UTC, merged